### ISSUE TITLE
Logic TODO Items

### ISSUE THREAD

**Issue by TrevorJTClarke** [Cron-Near/contracts#12]
* [x] Change storage keys to enums
* [x] Add admin fns to manage settings
* [x] paused to fns
* [x] Add asserts to check cadence can be parsed
* [x] Change OOP, be careful on rewind execution!
* [x] How can this promise execute and allow panics?
* [x] Adjust this to get slot from treemap floor?
* [x] update state, post pop
* [x] Process task exit, if no future task can execute
* [x] Change to real gas used
* [x] assert that attached deposit is enough to cover storage cost. This is to protect from storage attack.
